/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ext_blaster.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ext_blaster.pb-c.h"
void   ext_blaster__wifi_blast_result__health_metrics__load_avg__init
                     (ExtBlaster__WifiBlastResult__HealthMetrics__LoadAvg         *message)
{
  static const ExtBlaster__WifiBlastResult__HealthMetrics__LoadAvg init_value = EXT_BLASTER__WIFI_BLAST_RESULT__HEALTH_METRICS__LOAD_AVG__INIT;
  *message = init_value;
}
void   ext_blaster__wifi_blast_result__health_metrics__init
                     (ExtBlaster__WifiBlastResult__HealthMetrics         *message)
{
  static const ExtBlaster__WifiBlastResult__HealthMetrics init_value = EXT_BLASTER__WIFI_BLAST_RESULT__HEALTH_METRICS__INIT;
  *message = init_value;
}
void   ext_blaster__wifi_blast_result__radio_metrics__init
                     (ExtBlaster__WifiBlastResult__RadioMetrics         *message)
{
  static const ExtBlaster__WifiBlastResult__RadioMetrics init_value = EXT_BLASTER__WIFI_BLAST_RESULT__RADIO_METRICS__INIT;
  *message = init_value;
}
void   ext_blaster__wifi_blast_result__device_metrics__init
                     (ExtBlaster__WifiBlastResult__DeviceMetrics         *message)
{
  static const ExtBlaster__WifiBlastResult__DeviceMetrics init_value = EXT_BLASTER__WIFI_BLAST_RESULT__DEVICE_METRICS__INIT;
  *message = init_value;
}
void   ext_blaster__wifi_blast_result__status__init
                     (ExtBlaster__WifiBlastResult__Status         *message)
{
  static const ExtBlaster__WifiBlastResult__Status init_value = EXT_BLASTER__WIFI_BLAST_RESULT__STATUS__INIT;
  *message = init_value;
}
void   ext_blaster__wifi_blast_result__init
                     (ExtBlaster__WifiBlastResult         *message)
{
  static const ExtBlaster__WifiBlastResult init_value = EXT_BLASTER__WIFI_BLAST_RESULT__INIT;
  *message = init_value;
}
size_t ext_blaster__wifi_blast_result__get_packed_size
                     (const ExtBlaster__WifiBlastResult *message)
{
  assert(message->base.descriptor == &ext_blaster__wifi_blast_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ext_blaster__wifi_blast_result__pack
                     (const ExtBlaster__WifiBlastResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ext_blaster__wifi_blast_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ext_blaster__wifi_blast_result__pack_to_buffer
                     (const ExtBlaster__WifiBlastResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ext_blaster__wifi_blast_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExtBlaster__WifiBlastResult *
       ext_blaster__wifi_blast_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExtBlaster__WifiBlastResult *)
     protobuf_c_message_unpack (&ext_blaster__wifi_blast_result__descriptor,
                                allocator, len, data);
}
void   ext_blaster__wifi_blast_result__free_unpacked
                     (ExtBlaster__WifiBlastResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ext_blaster__wifi_blast_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ext_blaster__wifi_blast_result__health_metrics__load_avg__field_descriptors[3] =
{
  {
    "one",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(ExtBlaster__WifiBlastResult__HealthMetrics__LoadAvg, has_one),
    offsetof(ExtBlaster__WifiBlastResult__HealthMetrics__LoadAvg, one),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "five",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(ExtBlaster__WifiBlastResult__HealthMetrics__LoadAvg, has_five),
    offsetof(ExtBlaster__WifiBlastResult__HealthMetrics__LoadAvg, five),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fifteen",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(ExtBlaster__WifiBlastResult__HealthMetrics__LoadAvg, has_fifteen),
    offsetof(ExtBlaster__WifiBlastResult__HealthMetrics__LoadAvg, fifteen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ext_blaster__wifi_blast_result__health_metrics__load_avg__field_indices_by_name[] = {
  2,   /* field[2] = fifteen */
  1,   /* field[1] = five */
  0,   /* field[0] = one */
};
static const ProtobufCIntRange ext_blaster__wifi_blast_result__health_metrics__load_avg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ext_blaster__wifi_blast_result__health_metrics__load_avg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ext_blaster.WifiBlastResult.HealthMetrics.LoadAvg",
  "LoadAvg",
  "ExtBlaster__WifiBlastResult__HealthMetrics__LoadAvg",
  "ext_blaster",
  sizeof(ExtBlaster__WifiBlastResult__HealthMetrics__LoadAvg),
  3,
  ext_blaster__wifi_blast_result__health_metrics__load_avg__field_descriptors,
  ext_blaster__wifi_blast_result__health_metrics__load_avg__field_indices_by_name,
  1,  ext_blaster__wifi_blast_result__health_metrics__load_avg__number_ranges,
  (ProtobufCMessageInit) ext_blaster__wifi_blast_result__health_metrics__load_avg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ext_blaster__wifi_blast_result__health_metrics__field_descriptors[3] =
{
  {
    "cpu_util",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ExtBlaster__WifiBlastResult__HealthMetrics, has_cpu_util),
    offsetof(ExtBlaster__WifiBlastResult__HealthMetrics, cpu_util),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_util",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ExtBlaster__WifiBlastResult__HealthMetrics, has_mem_util),
    offsetof(ExtBlaster__WifiBlastResult__HealthMetrics, mem_util),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_avg",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ExtBlaster__WifiBlastResult__HealthMetrics, load_avg),
    &ext_blaster__wifi_blast_result__health_metrics__load_avg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ext_blaster__wifi_blast_result__health_metrics__field_indices_by_name[] = {
  0,   /* field[0] = cpu_util */
  2,   /* field[2] = load_avg */
  1,   /* field[1] = mem_util */
};
static const ProtobufCIntRange ext_blaster__wifi_blast_result__health_metrics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ext_blaster__wifi_blast_result__health_metrics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ext_blaster.WifiBlastResult.HealthMetrics",
  "HealthMetrics",
  "ExtBlaster__WifiBlastResult__HealthMetrics",
  "ext_blaster",
  sizeof(ExtBlaster__WifiBlastResult__HealthMetrics),
  3,
  ext_blaster__wifi_blast_result__health_metrics__field_descriptors,
  ext_blaster__wifi_blast_result__health_metrics__field_indices_by_name,
  1,  ext_blaster__wifi_blast_result__health_metrics__number_ranges,
  (ProtobufCMessageInit) ext_blaster__wifi_blast_result__health_metrics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ext_blaster__wifi_blast_result__radio_metrics__field_descriptors[8] =
{
  {
    "noise_floor",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, has_noise_floor),
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, noise_floor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel_utilization",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, has_channel_utilization),
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, channel_utilization),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activity_factor",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, has_activity_factor),
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, activity_factor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "carriersense_threshold_exceeded",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, has_carriersense_threshold_exceeded),
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, carriersense_threshold_exceeded),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, has_channel),
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_standard",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, has_wifi_standard),
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, wifi_standard),
    &ext_blaster__wi_fi_standard__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chan_width",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, has_chan_width),
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, chan_width),
    &ext_blaster__chan_width__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radio_band",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, has_radio_band),
    offsetof(ExtBlaster__WifiBlastResult__RadioMetrics, radio_band),
    &ext_blaster__radio_band_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ext_blaster__wifi_blast_result__radio_metrics__field_indices_by_name[] = {
  2,   /* field[2] = activity_factor */
  3,   /* field[3] = carriersense_threshold_exceeded */
  6,   /* field[6] = chan_width */
  4,   /* field[4] = channel */
  1,   /* field[1] = channel_utilization */
  0,   /* field[0] = noise_floor */
  7,   /* field[7] = radio_band */
  5,   /* field[5] = wifi_standard */
};
static const ProtobufCIntRange ext_blaster__wifi_blast_result__radio_metrics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ext_blaster__wifi_blast_result__radio_metrics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ext_blaster.WifiBlastResult.RadioMetrics",
  "RadioMetrics",
  "ExtBlaster__WifiBlastResult__RadioMetrics",
  "ext_blaster",
  sizeof(ExtBlaster__WifiBlastResult__RadioMetrics),
  8,
  ext_blaster__wifi_blast_result__radio_metrics__field_descriptors,
  ext_blaster__wifi_blast_result__radio_metrics__field_indices_by_name,
  1,  ext_blaster__wifi_blast_result__radio_metrics__number_ranges,
  (ProtobufCMessageInit) ext_blaster__wifi_blast_result__radio_metrics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ext_blaster__wifi_blast_result__device_metrics__field_descriptors[7] =
{
  {
    "client_mac",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, client_mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, has_rssi),
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_phyrate",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, has_tx_phyrate),
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, tx_phyrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_phyrate",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, has_rx_phyrate),
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, rx_phyrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "snr",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, has_snr),
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, snr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "throughput_samples",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, n_throughput_samples),
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, throughput_samples),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_packet_retransmissions",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, n_tx_packet_retransmissions),
    offsetof(ExtBlaster__WifiBlastResult__DeviceMetrics, tx_packet_retransmissions),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ext_blaster__wifi_blast_result__device_metrics__field_indices_by_name[] = {
  0,   /* field[0] = client_mac */
  1,   /* field[1] = rssi */
  3,   /* field[3] = rx_phyrate */
  4,   /* field[4] = snr */
  5,   /* field[5] = throughput_samples */
  6,   /* field[6] = tx_packet_retransmissions */
  2,   /* field[2] = tx_phyrate */
};
static const ProtobufCIntRange ext_blaster__wifi_blast_result__device_metrics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ext_blaster__wifi_blast_result__device_metrics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ext_blaster.WifiBlastResult.DeviceMetrics",
  "DeviceMetrics",
  "ExtBlaster__WifiBlastResult__DeviceMetrics",
  "ext_blaster",
  sizeof(ExtBlaster__WifiBlastResult__DeviceMetrics),
  7,
  ext_blaster__wifi_blast_result__device_metrics__field_descriptors,
  ext_blaster__wifi_blast_result__device_metrics__field_indices_by_name,
  1,  ext_blaster__wifi_blast_result__device_metrics__number_ranges,
  (ProtobufCMessageInit) ext_blaster__wifi_blast_result__device_metrics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ext_blaster__wifi_blast_result__status__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ExtBlaster__WifiBlastResult__Status, code),
    &ext_blaster__result_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExtBlaster__WifiBlastResult__Status, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ext_blaster__wifi_blast_result__status__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = description */
};
static const ProtobufCIntRange ext_blaster__wifi_blast_result__status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ext_blaster__wifi_blast_result__status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ext_blaster.WifiBlastResult.Status",
  "Status",
  "ExtBlaster__WifiBlastResult__Status",
  "ext_blaster",
  sizeof(ExtBlaster__WifiBlastResult__Status),
  2,
  ext_blaster__wifi_blast_result__status__field_descriptors,
  ext_blaster__wifi_blast_result__status__field_indices_by_name,
  1,  ext_blaster__wifi_blast_result__status__number_ranges,
  (ProtobufCMessageInit) ext_blaster__wifi_blast_result__status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ext_blaster__wifi_blast_result__field_descriptors[7] =
{
  {
    "time_stamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ExtBlaster__WifiBlastResult, has_time_stamp),
    offsetof(ExtBlaster__WifiBlastResult, time_stamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plan_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExtBlaster__WifiBlastResult, plan_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "step_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ExtBlaster__WifiBlastResult, has_step_id),
    offsetof(ExtBlaster__WifiBlastResult, step_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health_metrics",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ExtBlaster__WifiBlastResult, health_metrics),
    &ext_blaster__wifi_blast_result__health_metrics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radio_metrics",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ExtBlaster__WifiBlastResult, radio_metrics),
    &ext_blaster__wifi_blast_result__radio_metrics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_metrics",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ExtBlaster__WifiBlastResult, device_metrics),
    &ext_blaster__wifi_blast_result__device_metrics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ExtBlaster__WifiBlastResult, status),
    &ext_blaster__wifi_blast_result__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ext_blaster__wifi_blast_result__field_indices_by_name[] = {
  5,   /* field[5] = device_metrics */
  3,   /* field[3] = health_metrics */
  1,   /* field[1] = plan_id */
  4,   /* field[4] = radio_metrics */
  6,   /* field[6] = status */
  2,   /* field[2] = step_id */
  0,   /* field[0] = time_stamp */
};
static const ProtobufCIntRange ext_blaster__wifi_blast_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ext_blaster__wifi_blast_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ext_blaster.WifiBlastResult",
  "WifiBlastResult",
  "ExtBlaster__WifiBlastResult",
  "ext_blaster",
  sizeof(ExtBlaster__WifiBlastResult),
  7,
  ext_blaster__wifi_blast_result__field_descriptors,
  ext_blaster__wifi_blast_result__field_indices_by_name,
  1,  ext_blaster__wifi_blast_result__number_ranges,
  (ProtobufCMessageInit) ext_blaster__wifi_blast_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ext_blaster__radio_band_type__enum_values_by_number[5] =
{
  { "BAND_UNKNOWN", "EXT_BLASTER__RADIO_BAND_TYPE__BAND_UNKNOWN", 0 },
  { "BAND2G", "EXT_BLASTER__RADIO_BAND_TYPE__BAND2G", 1 },
  { "BAND5G", "EXT_BLASTER__RADIO_BAND_TYPE__BAND5G", 2 },
  { "BAND5GL", "EXT_BLASTER__RADIO_BAND_TYPE__BAND5GL", 3 },
  { "BAND5GU", "EXT_BLASTER__RADIO_BAND_TYPE__BAND5GU", 4 },
};
static const ProtobufCIntRange ext_blaster__radio_band_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex ext_blaster__radio_band_type__enum_values_by_name[5] =
{
  { "BAND2G", 1 },
  { "BAND5G", 2 },
  { "BAND5GL", 3 },
  { "BAND5GU", 4 },
  { "BAND_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor ext_blaster__radio_band_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ext_blaster.RadioBandType",
  "RadioBandType",
  "ExtBlaster__RadioBandType",
  "ext_blaster",
  5,
  ext_blaster__radio_band_type__enum_values_by_number,
  5,
  ext_blaster__radio_band_type__enum_values_by_name,
  1,
  ext_blaster__radio_band_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ext_blaster__wi_fi_standard__enum_values_by_number[7] =
{
  { "WIFI_STD_UNKNOWN", "EXT_BLASTER__WI_FI_STANDARD__WIFI_STD_UNKNOWN", 0 },
  { "WIFI_STD_80211_A", "EXT_BLASTER__WI_FI_STANDARD__WIFI_STD_80211_A", 1 },
  { "WIFI_STD_80211_B", "EXT_BLASTER__WI_FI_STANDARD__WIFI_STD_80211_B", 2 },
  { "WIFI_STD_80211_G", "EXT_BLASTER__WI_FI_STANDARD__WIFI_STD_80211_G", 3 },
  { "WIFI_STD_80211_N", "EXT_BLASTER__WI_FI_STANDARD__WIFI_STD_80211_N", 4 },
  { "WIFI_STD_80211_AC", "EXT_BLASTER__WI_FI_STANDARD__WIFI_STD_80211_AC", 5 },
  { "WIFI_STD_80211_AX", "EXT_BLASTER__WI_FI_STANDARD__WIFI_STD_80211_AX", 6 },
};
static const ProtobufCIntRange ext_blaster__wi_fi_standard__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex ext_blaster__wi_fi_standard__enum_values_by_name[7] =
{
  { "WIFI_STD_80211_A", 1 },
  { "WIFI_STD_80211_AC", 5 },
  { "WIFI_STD_80211_AX", 6 },
  { "WIFI_STD_80211_B", 2 },
  { "WIFI_STD_80211_G", 3 },
  { "WIFI_STD_80211_N", 4 },
  { "WIFI_STD_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor ext_blaster__wi_fi_standard__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ext_blaster.WiFiStandard",
  "WiFiStandard",
  "ExtBlaster__WiFiStandard",
  "ext_blaster",
  7,
  ext_blaster__wi_fi_standard__enum_values_by_number,
  7,
  ext_blaster__wi_fi_standard__enum_values_by_name,
  1,
  ext_blaster__wi_fi_standard__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ext_blaster__chan_width__enum_values_by_number[8] =
{
  { "CHAN_WIDTH_UNKNOWN", "EXT_BLASTER__CHAN_WIDTH__CHAN_WIDTH_UNKNOWN", 0 },
  { "CHAN_WIDTH_20MHZ", "EXT_BLASTER__CHAN_WIDTH__CHAN_WIDTH_20MHZ", 1 },
  { "CHAN_WIDTH_40MHZ", "EXT_BLASTER__CHAN_WIDTH__CHAN_WIDTH_40MHZ", 2 },
  { "CHAN_WIDTH_40MHZ_ABOVE", "EXT_BLASTER__CHAN_WIDTH__CHAN_WIDTH_40MHZ_ABOVE", 3 },
  { "CHAN_WIDTH_40MHZ_BELOW", "EXT_BLASTER__CHAN_WIDTH__CHAN_WIDTH_40MHZ_BELOW", 4 },
  { "CHAN_WIDTH_80MHZ", "EXT_BLASTER__CHAN_WIDTH__CHAN_WIDTH_80MHZ", 5 },
  { "CHAN_WIDTH_160MHZ", "EXT_BLASTER__CHAN_WIDTH__CHAN_WIDTH_160MHZ", 6 },
  { "CHAN_WIDTH_80_PLUS_80MHZ", "EXT_BLASTER__CHAN_WIDTH__CHAN_WIDTH_80_PLUS_80MHZ", 7 },
};
static const ProtobufCIntRange ext_blaster__chan_width__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex ext_blaster__chan_width__enum_values_by_name[8] =
{
  { "CHAN_WIDTH_160MHZ", 6 },
  { "CHAN_WIDTH_20MHZ", 1 },
  { "CHAN_WIDTH_40MHZ", 2 },
  { "CHAN_WIDTH_40MHZ_ABOVE", 3 },
  { "CHAN_WIDTH_40MHZ_BELOW", 4 },
  { "CHAN_WIDTH_80MHZ", 5 },
  { "CHAN_WIDTH_80_PLUS_80MHZ", 7 },
  { "CHAN_WIDTH_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor ext_blaster__chan_width__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ext_blaster.ChanWidth",
  "ChanWidth",
  "ExtBlaster__ChanWidth",
  "ext_blaster",
  8,
  ext_blaster__chan_width__enum_values_by_number,
  8,
  ext_blaster__chan_width__enum_values_by_name,
  1,
  ext_blaster__chan_width__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ext_blaster__result_code__enum_values_by_number[3] =
{
  { "RESULT_CODE_UNDEFINED", "EXT_BLASTER__RESULT_CODE__RESULT_CODE_UNDEFINED", 0 },
  { "RESULT_CODE_SUCCEED", "EXT_BLASTER__RESULT_CODE__RESULT_CODE_SUCCEED", 1 },
  { "RESULT_CODE_ERROR", "EXT_BLASTER__RESULT_CODE__RESULT_CODE_ERROR", 2 },
};
static const ProtobufCIntRange ext_blaster__result_code__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ext_blaster__result_code__enum_values_by_name[3] =
{
  { "RESULT_CODE_ERROR", 2 },
  { "RESULT_CODE_SUCCEED", 1 },
  { "RESULT_CODE_UNDEFINED", 0 },
};
const ProtobufCEnumDescriptor ext_blaster__result_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ext_blaster.ResultCode",
  "ResultCode",
  "ExtBlaster__ResultCode",
  "ext_blaster",
  3,
  ext_blaster__result_code__enum_values_by_number,
  3,
  ext_blaster__result_code__enum_values_by_name,
  1,
  ext_blaster__result_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
