#!/bin/sh
######################################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#  Copyright 2020 RDK Management
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################################################################
MODEL_NUM=`grep MODEL_NUM /etc/device.properties | cut -d "=" -f2`
OPENSYNC_ENABLE=`syscfg get opensync`
OPENSYNC_44_ENABLE=`syscfg get opensync_44`
OPENSYNC_SCRIPTS_PATH=/usr/opensync/scripts
HAL_WRAPPER_ENABLE=`syscfg get ow_core_thread`
platform_checks()
{
if [ "$MODEL_NUM" == "DPC3941" ] || [ "$MODEL_NUM" == "DPC3939" ]; then
 if [ "$OPENSYNC_ENABLE" == "true" ];then
  echo "Opensync mode enabled"
  DOWNLOAD_PATH_OPENSYNC="/tmp/plume_dnld/usr/opensync/"
  WORKING_PATH_OPENSYNC="/usr/opensync/" 
fi
fi 
}
is_opensync_name()
{
    pids_array=`pidof ovsdb-server`
    for pid in $pids_array ; do
        if grep opensync /proc/$pid/cmdline ; then
            return 0
        fi
    done
    return 1
}
if [ $# -eq 0 ]; then
 echo "No arguments passed"
 exit 0
else
 platform_checks
  if [ "$OPENSYNC_44_ENABLE" == "true" ]
 then
    echo "OPENSYNC_44_ENABLE is true"
    OPENSYNC_SCRIPTS_PATH=/usr/opensync_44/scripts
 fi
 if [ "$OPENSYNC_ENABLE" == "true" ] || [ -f /etc/onewifi_enabled ] || [ -f /etc/WFO_enabled ];then
    export SM_WIFI_STATS_DISABLE=$HAL_WRAPPER_ENABLE
    if [ -z "$(pidof ovsdb-server)" ]
    then
         $OPENSYNC_SCRIPTS_PATH/managers.init $1
    else is_opensync_name
         $OPENSYNC_SCRIPTS_PATH/managers.init $1
    fi
 fi
fi
