name: Build Check on Arm64

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        path: 'OneWifi'

    - name: Clone unified-wifi-mesh repository
      run: |
        mkdir -p easymesh_project
        git clone https://github.com/rdkcentral/unified-wifi-mesh.git easymesh_project/unified-wifi-mesh
        mv OneWifi easymesh_project/OneWifi

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential \
                                cmake \
                                python3 \
                                python3-pip \
                                git \
                                vim \
                                libev-dev \
                                libjansson-dev \
                                zlib1g-dev \
                                libnl-3-dev \
                                libnl-genl-3-dev \
                                libnl-route-3-dev \
                                libavro-dev \
                                libcjson1 libcjson-dev \
                                libssl-dev \
                                uuid-dev \
                                libmysqlcppconn-dev \
                                libreadline-dev \
                                iptables \
                                mariadb-server \
                                gnupg \
                                file \
                                golang

    - name: Setup OneWiFi
      working-directory: easymesh_project/OneWifi
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        make -f build/linux/makefile setup
      env:
        GITHUB_ACTOR: ${{ github.actor }}

    - name: Build OneWiFi
      working-directory: easymesh_project/OneWifi
      run: |
        make -f build/linux/makefile all
